# Cloud Build configuration for EsferaZap
# Automatically deploys to Cloud Run when pushing to main branch

substitutions:
  _SERVICE_NAME: esferazap
  _REGION: us-central1
  _IMAGE_NAME: gcr.io/${PROJECT_ID}/esferazap

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}:${COMMIT_SHA}'
      - '-t'
      - '${_IMAGE_NAME}:latest'
      - '.'
    timeout: '1200s'

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_IMAGE_NAME}'
    timeout: '600s'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_IMAGE_NAME}:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '100'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,FIREBASE_PROJECT_ID=login-ee5ed'
      - '--set-secrets'
      - 'FIREBASE_PRIVATE_KEY=firebase-private-key:latest,FIREBASE_CLIENT_EMAIL=firebase-client-email:latest'
    timeout: '600s'

  # Step 4: Configure traffic to new revision
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - '${_SERVICE_NAME}'
      - '--to-latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
  
# Timeout for entire build
timeout: '2400s'

# Store build logs in Cloud Storage
logsBucket: 'gs://esferazap-build-logs'

# Artifacts to store
artifacts:
  objects:
    location: 'gs://esferazap-build-artifacts'
    paths:
      - 'dist/**/*'