# Cloud Build configuration for automatic deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/esferazap-backend:$COMMIT_SHA', '.']
    
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/esferazap-backend:$COMMIT_SHA']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'esferazap-backend'
      - '--image=gcr.io/$PROJECT_ID/esferazap-backend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--port=8080'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--max-instances=10'
      - '--min-instances=1'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-secrets=DATABASE_URL=esferazap-db-url:latest,GEMINI_API_KEY=gemini-api-key:latest,SESSION_SECRET=session-secret:latest'
      - '--service-account=esferazap-backend@$PROJECT_ID.iam.gserviceaccount.com'

# Tag the image as latest
images:
  - 'gcr.io/$PROJECT_ID/esferazap-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/esferazap-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'